# Sample data
# - title: Title of the launcher
#   description: Description of the launcher
#   source: Path to the resource
#   type: Type of the resource
#   openWith: Custom opener
#   icon: Path to the svg icon