name: jupyter_app_launcher_docs
channels:
  - conda-forge
dependencies:
  - python=3.*
  - nodejs
  - jupyter_sphinx
  - sphinx<8
  - pydata-sphinx-theme
  - nbsphinx
  - nbsphinx-link
  - yarn
  - myst-parser
